---
title: "Natural Language Processing"
description: "Grasp how automatically analyze documents"
date: 2025-11-17
layout: full
toc: true
toc-expand: 3
---

## Activities

- {{< iconify fa6-solid lightbulb size=18px >}} **Monday**:
  - Instructor-led deep-dive on natural language processing
  - As needed, instructor review of previous technical topics
- {{< iconify fa6-solid people-line size=18px >}} **Wednesday**:
  - Instructor-led deep-dive on natural language processing
  - As needed, instructor review of previous technical topics
- {{< iconify fa6-solid gears size=18px >}} **Wednesday Laboratory**:
  - Release the third document engineering tool-building project
  - Students meet with the student technical leaders
  - Students give in-person demonstration to course instructor
- {{< iconify fa6-solid gears size=18px >}} **Friday**:
  - Use installed software tools for document engineering skill-check five
  - Complete skill-check five during the in-person classroom session
  - Please review [Week One: Introduction to Document
  Engineering](../../slides/weekone/) for a list of necessary software tools

## Slides

```{=html}
<iframe class="slide-deck" src="../../slides/weekthirteen/"></iframe>
```

{{< iconify majesticons presentation-play size=18px >}} Full Screen: [Week
Thirteen: Natural Language Processing for Document
Engineering](../../slides/weekthirteen/)
