---
title: "Regular Expressions"
description: "Learn how to perform pattern matching"
date: 2025-11-10
layout: full
toc: true
toc-expand: 3
---

## Activities

- {{< iconify fa6-solid lightbulb size=18px >}} **Monday**:
  - Instructor-led deep-dive on regular expressions
  - As needed, instructor review of previous technical topics
- {{< iconify fa6-solid people-line size=18px >}} **Wednesday**:
  - Instructor-led deep-dive on regular expressions
  - As needed, instructor review of previous technical topics
- {{< iconify fa6-solid gears size=18px >}} **Wednesday Laboratory**:
  - Continue working on second document engineering tool-building project
  - Students meet with the student technical leaders
  - Students give in-person demonstration to course instructor
  - Second phase of the document engineering project due by 11:59 PM
- {{< iconify fa6-solid gears size=18px >}} **Friday**:
  - Instructor-led deep-dive on regular expressions
  - As needed, instructor review of previous technical topics

## Slides

```{=html}
<iframe class="slide-deck" src="../../slides/weektwelve/"></iframe>
```

{{< iconify majesticons presentation-play size=18px >}} Full Screen: [Week
Twelve: Regular Expressions for Document Engineering](../../slides/weektwelve/)
